packages:
  - "lib/lib/*"
  - "artifacts/artifacts/*"

onlyBuiltDependencies:
  - esbuild

catalog:
  "@replit/vite-plugin-cartographer": "^0.5.1"
  "@replit/vite-plugin-dev-banner": "^0.1.2"
  "@replit/vite-plugin-runtime-error-modal": "^0.0.6"
  "@tailwindcss/vite": "^4.1.4"
  "@tanstack/react-query": "^5.74.4"
  "@types/node": "^22.14.1"
  "@types/react": "^19.1.2"
  "@types/react-dom": "^19.1.2"
  "@vitejs/plugin-react": "^4.4.1"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "drizzle-orm": "^0.41.0"
  "framer-motion": "^12.7.3"
  "lucide-react": "^0.487.0"
  "react": "^19.1.0"
  "react-dom": "^19.1.0"
  "tailwind-merge": "^3.2.0"
  "tailwindcss": "^4.1.4"
  "typescript": "^5.8.3"
  "vite": "^6.3.2"
  "zod": "^3.24.3"
